name: Deploy Web VM with Manual ISO Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup directories
      run: |
        mkdir -p vm/bios vm/storage vm/js vm/css

    - name: Download v86 library
      run: |
        curl -L -o vm/v86.js https://cdn.jsdelivr.net/npm/v86@0.2.0/build/libv86.js

    - name: Create placeholder BIOS files
      run: |
        touch vm/bios/seabios.bin
        touch vm/bios/vgabios.bin

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
